//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ApaGroup.Framework.Basis.Enumerations;
using ApaGroup.Framework.Dal.DataStructure.Attributes;
using ApaGroup.Framework.Dal.DataStructure.Securities.Attributes;
using ApaGroup.Framework.Dal.DataStructure.Cores.DataModels;
using ApaGroup.Framework.Dal.DataStructure.Enumerations;
using System;
using System.Runtime.Serialization;

namespace ApaGroup.Framework.Dal.DataStructure.Securities.DataModels
{
    
    public partial class SecurityAccountDataModelBase : DataModelBase
    {
    	#region Private Fields
    
    	private int _Id;
    
    	private byte[] _RowVersion;
    
    	private System.DateTime _CreateDate;
    
    	private System.DateTime _UpdateDate;
    
    	private int _UserId;
    
    	private Nullable<System.Guid> _Image;
    
    	private int _ChargeAmount;
    
    	private bool _Enable;
    
    	private string _AccountType;
    
    	#endregion
    
    	#region Public Properties
    
    	
        public override int Id { get{ return _Id; } set{ SetValue("Id", ref _Id, value); } }
    
    	
        public override byte[] RowVersion { get{ return _RowVersion; } set{ SetValue("RowVersion", ref _RowVersion, value); } }
    
    	
        public System.DateTime CreateDate { get{ return _CreateDate; } set{ SetValue("CreateDate", ref _CreateDate, value); } }
    
    	
        public System.DateTime UpdateDate { get{ return _UpdateDate; } set{ SetValue("UpdateDate", ref _UpdateDate, value); } }
    
    	
        public int UserId { get{ return _UserId; } set{ SetValue("UserId", ref _UserId, value); } }
    
    	
        public Nullable<System.Guid> Image { get{ return _Image; } set{ SetValue("Image", ref _Image, value); } }
    
    	
        public int ChargeAmount { get{ return _ChargeAmount; } set{ SetValue("ChargeAmount", ref _ChargeAmount, value); } }
    
    	
        public bool Enable { get{ return _Enable; } set{ SetValue("Enable", ref _Enable, value); } }
    
    	
        public string AccountType { get{ return _AccountType; } set{ SetValue("AccountType", ref _AccountType, value); } }
    
    	#endregion
    }
}
