//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApaGroup.Framework.Basis.EntityModels
{
    using System;
    using System.Collections.Generic;
    
    internal partial class LogDataModel
    {
        public int Id { get; set; }
        public System.DateTime IssueDate { get; set; }
        public string IssueContent { get; set; }
        public string Type { get; set; }
    }
}
