//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ApaGroup.Framework.Basis.Enumerations;
using ApaGroup.Framework.Dal.DataStructure.Attributes;
using ApaGroup.Framework.Dal.DataStructure.Securities.Attributes;
using ApaService.Framework.Dal.DataStructure.Cores.DataModels;
using ApaGroup.Framework.Dal.DataStructure.Enumerations;
using System;
using System.Runtime.Serialization;

namespace ApaService.Framework.Dal.DataStructure.DataModels
{
    [DatabaseObject("User")][DataModel][DataContract(IsReference = true)]
    public partial class AdministratorUserDataModel : ApasDataModelBase
    {
    	#region Private Fields
    
    	private int _Id;
    
    	private byte[] _RowVersion;
    
    	private string _Username;
    
    	private string _Type;
    
    	private string _Name;
    
    	private string _Family;
    
    	private string _Gender;
    
    	private string _PersonalCode;
    
    	private Nullable<System.DateTime> _Birthday;
    
    	private string _PhoneNumber;
    
    	private string _MobileNumber;
    
    	private string _Email;
    
    	private int _LocationId;
    
    	private string _Address;
    
    	private string _PostalCode;
    
    	#endregion
    
    	#region Public Properties
    
    	[DataMember]
        public override int Id { get{ return _Id; } set{ SetValue("Id", ref _Id, value); } }
    
    	[DataMember]
        public override byte[] RowVersion { get{ return _RowVersion; } set{ SetValue("RowVersion", ref _RowVersion, value); } }
    
    	[ValueChangePreventer][DataMember]
        public string Username { get{ return _Username; } set{ SetValue("Username", ref _Username, value); } }
    
    	[ValueChangePreventer][DataMember]
        public string Type { get{ return _Type; } set{ SetValue("Type", ref _Type, value); } }
    
    	[DataMember]
        public string Name { get{ return _Name; } set{ SetValue("Name", ref _Name, value); } }
    
    	[DataMember]
        public string Family { get{ return _Family; } set{ SetValue("Family", ref _Family, value); } }
    
    	[ValueChangePreventer][DataMember]
        public string Gender { get{ return _Gender; } set{ SetValue("Gender", ref _Gender, value); } }
    
    	[ValueChangePreventer][DataMember]
        public string PersonalCode { get{ return _PersonalCode; } set{ SetValue("PersonalCode", ref _PersonalCode, value); } }
    
    	[DataMember]
        public Nullable<System.DateTime> Birthday { get{ return _Birthday; } set{ SetValue("Birthday", ref _Birthday, value); } }
    
    	[DataMember]
        public string PhoneNumber { get{ return _PhoneNumber; } set{ SetValue("PhoneNumber", ref _PhoneNumber, value); } }
    
    	[DataMember]
        public string MobileNumber { get{ return _MobileNumber; } set{ SetValue("MobileNumber", ref _MobileNumber, value); } }
    
    	[DataMember]
        public string Email { get{ return _Email; } set{ SetValue("Email", ref _Email, value); } }
    
    	[DataMember]
        public int LocationId { get{ return _LocationId; } set{ SetValue("LocationId", ref _LocationId, value); } }
    
    	[DataMember]
        public string Address { get{ return _Address; } set{ SetValue("Address", ref _Address, value); } }
    
    	[DataMember]
        public string PostalCode { get{ return _PostalCode; } set{ SetValue("PostalCode", ref _PostalCode, value); } }
    
    	#endregion
    }
}
