//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ApaGroup.Framework.Basis.Enumerations;
using ApaGroup.Framework.Dal.DataStructure.Attributes;
using ApaGroup.Framework.Dal.DataStructure.Securities.Attributes;
using ApaService.Framework.Dal.DataStructure.Cores.DataModels;
using ApaGroup.Framework.Dal.DataStructure.Enumerations;
using System;
using System.Runtime.Serialization;

namespace ApaService.Framework.Dal.DataStructure.DataModels
{
    [DatabaseObject("Basket")][DataModel][DataContract(IsReference = true)][WorkflowProperty("Status", false)]
    public partial class AdministratorBasketDataModel : ApasDataModelBase
    {
    	#region Private Fields
    
    	private int _Id;
    
    	private byte[] _RowVersion;
    
    	private System.DateTime _CreateDate;
    
    	private System.DateTime _UpdateDate;
    
    	private int _ShopId;
    
    	private int _AccountBuyerId;
    
    	private int _SourceLocationId;
    
    	private int _DestinationLocationId;
    
    	private int _ShopDeliveryMethodId;
    
    	private int _ShopPaymentMethodId;
    
    	private string _Fullname;
    
    	private string _PhoneNumber;
    
    	private string _MobileNumber;
    
    	private string _DestinationAddress;
    
    	private string _Status;
    
    	private string _StatusDescriptions;
    
    	private string _Workflow;
    
    	private string _UserDescription;
    
    	private bool _IsTheUserDescriptionNeededToConfirm;
    
    	private int _TotalItemsOriginAmount;
    
    	private int _TotalItemsTaxAmount;
    
    	private int _TotalItemsDiscountAmount;
    
    	private int _DeliveryAmount;
    
    	private int _TaxAmount;
    
    	private int _DiscountAmount;
    
    	private int _ApaGroupCommissionAmount;
    
    	private int _FinalAmount;
    
    	#endregion
    
    	#region Public Properties
    
    	[DataMember]
        public override int Id { get{ return _Id; } set{ SetValue("Id", ref _Id, value); } }
    
    	[DataMember]
        public override byte[] RowVersion { get{ return _RowVersion; } set{ SetValue("RowVersion", ref _RowVersion, value); } }
    
    	[ValueChangePreventer][DataMember]
        public System.DateTime CreateDate { get{ return _CreateDate; } set{ SetValue("CreateDate", ref _CreateDate, value); } }
    
    	[DataMember]
        public System.DateTime UpdateDate { get{ return _UpdateDate; } set{ SetValue("UpdateDate", ref _UpdateDate, value); } }
    
    	[ValueChangePreventer][DataMember]
        public int ShopId { get{ return _ShopId; } set{ SetValue("ShopId", ref _ShopId, value); } }
    
    	[ValueChangePreventer][DataMember]
        public int AccountBuyerId { get{ return _AccountBuyerId; } set{ SetValue("AccountBuyerId", ref _AccountBuyerId, value); } }
    
    	[DataMember]
        public int SourceLocationId { get{ return _SourceLocationId; } set{ SetValue("SourceLocationId", ref _SourceLocationId, value); } }
    
    	[DataMember]
        public int DestinationLocationId { get{ return _DestinationLocationId; } set{ SetValue("DestinationLocationId", ref _DestinationLocationId, value); } }
    
    	[DataMember]
        public int ShopDeliveryMethodId { get{ return _ShopDeliveryMethodId; } set{ SetValue("ShopDeliveryMethodId", ref _ShopDeliveryMethodId, value); } }
    
    	[DataMember]
        public int ShopPaymentMethodId { get{ return _ShopPaymentMethodId; } set{ SetValue("ShopPaymentMethodId", ref _ShopPaymentMethodId, value); } }
    
    	[DataMember]
        public string Fullname { get{ return _Fullname; } set{ SetValue("Fullname", ref _Fullname, value); } }
    
    	[DataMember]
        public string PhoneNumber { get{ return _PhoneNumber; } set{ SetValue("PhoneNumber", ref _PhoneNumber, value); } }
    
    	[DataMember]
        public string MobileNumber { get{ return _MobileNumber; } set{ SetValue("MobileNumber", ref _MobileNumber, value); } }
    
    	[DataMember]
        public string DestinationAddress { get{ return _DestinationAddress; } set{ SetValue("DestinationAddress", ref _DestinationAddress, value); } }
    
    	[DataMember]
        public string Status { get{ return _Status; } set{ SetValue("Status", ref _Status, value); } }
    
    	[DataMember]
        public string StatusDescriptions { get{ return _StatusDescriptions; } set{ SetValue("StatusDescriptions", ref _StatusDescriptions, value); } }
    
    	[ValueChangePreventer][DataMember]
        public string Workflow { get{ return _Workflow; } set{ SetValue("Workflow", ref _Workflow, value); } }
    
    	[PropertyDefaultValue("")][DataMember]
        public string UserDescription { get{ return _UserDescription; } set{ SetValue("UserDescription", ref _UserDescription, value); } }
    
    	[PropertyDefaultValue(false)][DataMember]
        public bool IsTheUserDescriptionNeededToConfirm { get{ return _IsTheUserDescriptionNeededToConfirm; } set{ SetValue("IsTheUserDescriptionNeededToConfirm", ref _IsTheUserDescriptionNeededToConfirm, value); } }
    
    	[PropertyDefaultValue(0)][DataMember]
        public int TotalItemsOriginAmount { get{ return _TotalItemsOriginAmount; } set{ SetValue("TotalItemsOriginAmount", ref _TotalItemsOriginAmount, value); } }
    
    	[PropertyDefaultValue(0)][DataMember]
        public int TotalItemsTaxAmount { get{ return _TotalItemsTaxAmount; } set{ SetValue("TotalItemsTaxAmount", ref _TotalItemsTaxAmount, value); } }
    
    	[PropertyDefaultValue(0)][DataMember]
        public int TotalItemsDiscountAmount { get{ return _TotalItemsDiscountAmount; } set{ SetValue("TotalItemsDiscountAmount", ref _TotalItemsDiscountAmount, value); } }
    
    	[PropertyDefaultValue(0)][DataMember]
        public int DeliveryAmount { get{ return _DeliveryAmount; } set{ SetValue("DeliveryAmount", ref _DeliveryAmount, value); } }
    
    	[PropertyDefaultValue(0)][DataMember]
        public int TaxAmount { get{ return _TaxAmount; } set{ SetValue("TaxAmount", ref _TaxAmount, value); } }
    
    	[PropertyDefaultValue(0)][DataMember]
        public int DiscountAmount { get{ return _DiscountAmount; } set{ SetValue("DiscountAmount", ref _DiscountAmount, value); } }
    
    	[PropertyDefaultValue(0)][DataMember]
        public int ApaGroupCommissionAmount { get{ return _ApaGroupCommissionAmount; } set{ SetValue("ApaGroupCommissionAmount", ref _ApaGroupCommissionAmount, value); } }
    
    	[PropertyDefaultValue(0)][DataMember]
        public int FinalAmount { get{ return _FinalAmount; } set{ SetValue("FinalAmount", ref _FinalAmount, value); } }
    
    	#endregion
    }
}
