//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ApaGroup.Framework.Basis.Enumerations;
using ApaGroup.Framework.Dal.DataStructure.Attributes;
using ApaGroup.Framework.Dal.DataStructure.Securities.Attributes;
using ApaService.Framework.Dal.DataStructure.Cores.DataModels;
using ApaGroup.Framework.Dal.DataStructure.Enumerations;
using System;
using System.Runtime.Serialization;

namespace ApaService.Framework.Dal.DataStructure.DataModels
{
    [DatabaseObject("ProductStatistics")][DataModel][DataContract(IsReference = true)]
    public partial class AdministratorProductStatisticDataModel : ApasDataModelBase
    {
    	#region Private Fields
    
    	private int _Id;
    
    	private byte[] _RowVersion;
    
    	private int _LikeProduct;
    
    	private int _DislikeProduct;
    
    	private int _VisitCount;
    
    	private int _BoughtCount;
    
    	#endregion
    
    	#region Public Properties
    
    	[DataMember]
        public override int Id { get{ return _Id; } set{ SetValue("Id", ref _Id, value); } }
    
    	[DataMember]
        public override byte[] RowVersion { get{ return _RowVersion; } set{ SetValue("RowVersion", ref _RowVersion, value); } }
    
    	[PropertyDefaultValue(0)][DataMember]
        public int LikeProduct { get{ return _LikeProduct; } set{ SetValue("LikeProduct", ref _LikeProduct, value); } }
    
    	[PropertyDefaultValue(0)][DataMember]
        public int DislikeProduct { get{ return _DislikeProduct; } set{ SetValue("DislikeProduct", ref _DislikeProduct, value); } }
    
    	[PropertyDefaultValue(0)][DataMember]
        public int VisitCount { get{ return _VisitCount; } set{ SetValue("VisitCount", ref _VisitCount, value); } }
    
    	[PropertyDefaultValue(0)][DataMember]
        public int BoughtCount { get{ return _BoughtCount; } set{ SetValue("BoughtCount", ref _BoughtCount, value); } }
    
    	#endregion
    }
}
