//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ApaGroup.Framework.Basis.Enumerations;
using ApaGroup.Framework.Dal.DataStructure.Attributes;
using ApaGroup.Framework.Dal.DataStructure.Securities.Attributes;
using ApaService.Framework.Dal.DataStructure.Cores.DataModels;
using ApaGroup.Framework.Dal.DataStructure.Enumerations;
using System;
using System.Runtime.Serialization;

namespace ApaService.Framework.Dal.DataStructure.DataModels
{
    [DatabaseObject("AccountTransaction")][DataModel][DataContract(IsReference = true)]
    public partial class AdministratorAccountTransactionDataModel : AdministratorTransactionDataModelBase
    {
    	#region Private Fields
    
    	private int _AccountId;
    
    	#endregion
    
    	#region Public Properties
    
    	[ValueChangePreventer][DataMember]
        public int AccountId { get{ return _AccountId; } set{ SetValue("AccountId", ref _AccountId, value); } }
    
    	#endregion
    }
}
