//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ApaGroup.Framework.Basis.Enumerations;
using ApaGroup.Framework.Dal.DataStructure.Attributes;
using ApaGroup.Framework.Dal.DataStructure.Securities.Attributes;
using ApaService.Framework.Dal.DataStructure.Cores.DataModels;
using ApaGroup.Framework.Dal.DataStructure.Enumerations;
using System;
using System.Runtime.Serialization;

namespace ApaService.Framework.Dal.DataStructure.DataModels
{
    [DatabaseObject("Transaction")][DataModel][DataContract(IsReference = true)]
    public partial class AdministratorTransactionDataModelBase : ApasDataModelBase
    {
    	#region Private Fields
    
    	private int _Id;
    
    	private byte[] _RowVersion;
    
    	private System.DateTime _CreateDate;
    
    	private System.DateTime _UpdateDate;
    
    	private string _ReferenceNumber;
    
    	private string _BuyerAccountNumber;
    
    	private int _TotalAmount;
    
    	private int _ReverseAmount;
    
    	private string _TransactionState;
    
    	#endregion
    
    	#region Public Properties
    
    	[DataMember]
        public override int Id { get{ return _Id; } set{ SetValue("Id", ref _Id, value); } }
    
    	[DataMember]
        public override byte[] RowVersion { get{ return _RowVersion; } set{ SetValue("RowVersion", ref _RowVersion, value); } }
    
    	[ValueChangePreventer][DataMember]
        public System.DateTime CreateDate { get{ return _CreateDate; } set{ SetValue("CreateDate", ref _CreateDate, value); } }
    
    	[DataMember]
        public System.DateTime UpdateDate { get{ return _UpdateDate; } set{ SetValue("UpdateDate", ref _UpdateDate, value); } }
    
    	[ValueChangePreventer][DataMember]
        public string ReferenceNumber { get{ return _ReferenceNumber; } set{ SetValue("ReferenceNumber", ref _ReferenceNumber, value); } }
    
    	[ValueChangePreventer][DataMember]
        public string BuyerAccountNumber { get{ return _BuyerAccountNumber; } set{ SetValue("BuyerAccountNumber", ref _BuyerAccountNumber, value); } }
    
    	[ValueChangePreventer][DataMember]
        public int TotalAmount { get{ return _TotalAmount; } set{ SetValue("TotalAmount", ref _TotalAmount, value); } }
    
    	[PropertyDefaultValue(0)][DataMember]
        public int ReverseAmount { get{ return _ReverseAmount; } set{ SetValue("ReverseAmount", ref _ReverseAmount, value); } }
    
    	[ValueChangePreventer][DataMember]
        public string TransactionState { get{ return _TransactionState; } set{ SetValue("TransactionState", ref _TransactionState, value); } }
    
    	#endregion
    }
}
