//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ApaGroup.Framework.Basis.Enumerations;
using ApaGroup.Framework.Dal.DataStructure.Attributes;
using ApaGroup.Framework.Dal.DataStructure.Securities.Attributes;
using ApaService.Framework.Dal.DataStructure.Cores.DataModels;
using ApaGroup.Framework.Dal.DataStructure.Enumerations;
using System;
using System.Runtime.Serialization;

namespace ApaService.Framework.Dal.DataStructure.DataModels
{
    [DatabaseObject("ShopComment")][DataModel][DataContract(IsReference = true)]
    public partial class AdministratorShopCommentDataModel : ApasDataModelBase
    {
    	#region Private Fields
    
    	private int _Id;
    
    	private byte[] _RowVersion;
    
    	private int _ShopId;
    
    	private string _Username;
    
    	private string _CommentType;
    
    	private string _Comment;
    
    	#endregion
    
    	#region Public Properties
    
    	[DataMember]
        public override int Id { get{ return _Id; } set{ SetValue("Id", ref _Id, value); } }
    
    	[DataMember]
        public override byte[] RowVersion { get{ return _RowVersion; } set{ SetValue("RowVersion", ref _RowVersion, value); } }
    
    	[ValueChangePreventer][DataMember]
        public int ShopId { get{ return _ShopId; } set{ SetValue("ShopId", ref _ShopId, value); } }
    
    	[ValueChangePreventer][DataMember]
        public string Username { get{ return _Username; } set{ SetValue("Username", ref _Username, value); } }
    
    	[ValueChangePreventer][DataMember]
        public string CommentType { get{ return _CommentType; } set{ SetValue("CommentType", ref _CommentType, value); } }
    
    	[DataMember]
        public string Comment { get{ return _Comment; } set{ SetValue("Comment", ref _Comment, value); } }
    
    	#endregion
    }
}
