//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ApaGroup.Framework.Basis.Enumerations;
using ApaGroup.Framework.Dal.DataStructure.Attributes;
using ApaGroup.Framework.Dal.DataStructure.Securities.Attributes;
using ApaService.Framework.Dal.DataStructure.Cores.DataModels;
using ApaGroup.Framework.Dal.DataStructure.Enumerations;
using System;
using System.Runtime.Serialization;

namespace ApaService.Framework.Dal.DataStructure.DataModels
{
    [DatabaseObject("BasketItem")][DataModel][DataContract(IsReference = true)]
    public partial class AdministratorBasketItemDataModel : ApasDataModelBase
    {
    	#region Private Fields
    
    	private int _Id;
    
    	private byte[] _RowVersion;
    
    	private int _BasketId;
    
    	private int _ProductId;
    
    	private string _Ordered;
    
    	private int _OriginAmount;
    
    	private int _TaxAmount;
    
    	private int _DiscountAmount;
    
    	private int _FinalAmount;
    
    	private string _Description;
    
    	#endregion
    
    	#region Public Properties
    
    	[DataMember]
        public override int Id { get{ return _Id; } set{ SetValue("Id", ref _Id, value); } }
    
    	[DataMember]
        public override byte[] RowVersion { get{ return _RowVersion; } set{ SetValue("RowVersion", ref _RowVersion, value); } }
    
    	[ValueChangePreventer][DataMember]
        public int BasketId { get{ return _BasketId; } set{ SetValue("BasketId", ref _BasketId, value); } }
    
    	[ValueChangePreventer][DataMember]
        public int ProductId { get{ return _ProductId; } set{ SetValue("ProductId", ref _ProductId, value); } }
    
    	[ValueChangePreventer][DataMember]
        public string Ordered { get{ return _Ordered; } set{ SetValue("Ordered", ref _Ordered, value); } }
    
    	[PropertyDefaultValue(0)][DataMember]
        public int OriginAmount { get{ return _OriginAmount; } set{ SetValue("OriginAmount", ref _OriginAmount, value); } }
    
    	[PropertyDefaultValue(0)][DataMember]
        public int TaxAmount { get{ return _TaxAmount; } set{ SetValue("TaxAmount", ref _TaxAmount, value); } }
    
    	[PropertyDefaultValue(0)][DataMember]
        public int DiscountAmount { get{ return _DiscountAmount; } set{ SetValue("DiscountAmount", ref _DiscountAmount, value); } }
    
    	[PropertyDefaultValue(0)][DataMember]
        public int FinalAmount { get{ return _FinalAmount; } set{ SetValue("FinalAmount", ref _FinalAmount, value); } }
    
    	[PropertyDefaultValue("")][DataMember]
        public string Description { get{ return _Description; } set{ SetValue("Description", ref _Description, value); } }
    
    	#endregion
    }
}
