//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ApaGroup.Framework.Basis.Enumerations;
using ApaGroup.Framework.Dal.DataStructure.Attributes;
using ApaGroup.Framework.Dal.DataStructure.Securities.Attributes;
using ApaService.Framework.Dal.DataStructure.Cores.DataModels;
using ApaGroup.Framework.Dal.DataStructure.Enumerations;
using System;
using System.Runtime.Serialization;

namespace ApaService.Framework.Dal.DataStructure.DataModels
{
    [DatabaseObject("Shop")][DataModel][DataContract(IsReference = true)]
    public partial class AdministratorShopDataModel : ApasDataModelBase
    {
    	#region Private Fields
    
    	private int _Id;
    
    	private byte[] _RowVersion;
    
    	private System.DateTime _CreateDate;
    
    	private System.DateTime _UpdateDate;
    
    	private int _AccountSellerId;
    
    	private int _LocationId;
    
    	private bool _Enable;
    
    	private string _PersianName;
    
    	private string _EnglishName;
    
    	private string _SearchHelper;
    
    	private Nullable<System.Guid> _LogoIdentifier;
    
    	private bool _AreBasketsNeededToConfirm;
    
    	private string _ImageIdentifiers;
    
    	private string _Tax;
    
    	private string _Discount;
    
    	private string _ApaGroupCommission;
    
    	private string _Description;
    
    	#endregion
    
    	#region Public Properties
    
    	[DataMember]
        public override int Id { get{ return _Id; } set{ SetValue("Id", ref _Id, value); } }
    
    	[DataMember]
        public override byte[] RowVersion { get{ return _RowVersion; } set{ SetValue("RowVersion", ref _RowVersion, value); } }
    
    	[ValueChangePreventer][DataMember]
        public System.DateTime CreateDate { get{ return _CreateDate; } set{ SetValue("CreateDate", ref _CreateDate, value); } }
    
    	[DataMember]
        public System.DateTime UpdateDate { get{ return _UpdateDate; } set{ SetValue("UpdateDate", ref _UpdateDate, value); } }
    
    	[ValueChangePreventer][DataMember]
        public int AccountSellerId { get{ return _AccountSellerId; } set{ SetValue("AccountSellerId", ref _AccountSellerId, value); } }
    
    	[ValueChangePreventer][DataMember]
        public int LocationId { get{ return _LocationId; } set{ SetValue("LocationId", ref _LocationId, value); } }
    
    	[PropertyDefaultValue(false)][DataMember]
        public bool Enable { get{ return _Enable; } set{ SetValue("Enable", ref _Enable, value); } }
    
    	[DataMember]
        public string PersianName { get{ return _PersianName; } set{ SetValue("PersianName", ref _PersianName, value); } }
    
    	[PropertyDefaultValue("")][DataMember]
        public string EnglishName { get{ return _EnglishName; } set{ SetValue("EnglishName", ref _EnglishName, value); } }
    
    	[DataMember]
        public string SearchHelper { get{ return _SearchHelper; } set{ SetValue("SearchHelper", ref _SearchHelper, value); } }
    
    	[PropertyDefaultValue(null)][DataMember]
        public Nullable<System.Guid> LogoIdentifier { get{ return _LogoIdentifier; } set{ SetValue("LogoIdentifier", ref _LogoIdentifier, value); } }
    
    	[PropertyDefaultValue(false)][DataMember]
        public bool AreBasketsNeededToConfirm { get{ return _AreBasketsNeededToConfirm; } set{ SetValue("AreBasketsNeededToConfirm", ref _AreBasketsNeededToConfirm, value); } }
    
    	[DataMember]
        public string ImageIdentifiers { get{ return _ImageIdentifiers; } set{ SetValue("ImageIdentifiers", ref _ImageIdentifiers, value); } }
    
    	[PropertyDefaultValue(0)][DataMember]
        public string Tax { get{ return _Tax; } set{ SetValue("Tax", ref _Tax, value); } }
    
    	[PropertyDefaultValue(0)][DataMember]
        public string Discount { get{ return _Discount; } set{ SetValue("Discount", ref _Discount, value); } }
    
    	[PropertyDefaultValue(0)][DataMember]
        public string ApaGroupCommission { get{ return _ApaGroupCommission; } set{ SetValue("ApaGroupCommission", ref _ApaGroupCommission, value); } }
    
    	[PropertyDefaultValue("")][DataMember]
        public string Description { get{ return _Description; } set{ SetValue("Description", ref _Description, value); } }
    
    	#endregion
    }
}
