//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ApaGroup.Framework.Basis.Enumerations;
using ApaGroup.Framework.Dal.DataStructure.Attributes;
using ApaGroup.Framework.Dal.DataStructure.Securities.Attributes;
using ApaService.Framework.Dal.DataStructure.Cores.DataModels;
using ApaGroup.Framework.Dal.DataStructure.Enumerations;
using System;
using System.Runtime.Serialization;

namespace ApaService.Framework.Dal.DataStructure.DataModels
{
    [DatabaseObject("ProductNumerable")][DataModel][DataContract(IsReference = true)]
    public partial class AdministratorProductNumerableDataModelBase : AdministratorProductDataModelBase
    {
    	#region Private Fields
    
    	private int _Weight;
    
    	private string _Unit;
    
    	private Nullable<int> _Store;
    
    	private Nullable<int> _RetailUnitPriceAmount;
    
    	private string _RetailConditions;
    
    	private Nullable<int> _WholesaleUnitPriceAmount;
    
    	private string _WholesaleConditions;
    
    	private string _Tax;
    
    	private string _Discount;
    
    	#endregion
    
    	#region Public Properties
    
    	[DataMember]
        public int Weight { get{ return _Weight; } set{ SetValue("Weight", ref _Weight, value); } }
    
    	[DataMember]
        public string Unit { get{ return _Unit; } set{ SetValue("Unit", ref _Unit, value); } }
    
    	[PropertyDefaultValue(0)][DataMember]
        public Nullable<int> Store { get{ return _Store; } set{ SetValue("Store", ref _Store, value); } }
    
    	[PropertyDefaultValue(null)][DataMember]
        public Nullable<int> RetailUnitPriceAmount { get{ return _RetailUnitPriceAmount; } set{ SetValue("RetailUnitPriceAmount", ref _RetailUnitPriceAmount, value); } }
    
    	[DataMember]
        public string RetailConditions { get{ return _RetailConditions; } set{ SetValue("RetailConditions", ref _RetailConditions, value); } }
    
    	[PropertyDefaultValue(null)][DataMember]
        public Nullable<int> WholesaleUnitPriceAmount { get{ return _WholesaleUnitPriceAmount; } set{ SetValue("WholesaleUnitPriceAmount", ref _WholesaleUnitPriceAmount, value); } }
    
    	[DataMember]
        public string WholesaleConditions { get{ return _WholesaleConditions; } set{ SetValue("WholesaleConditions", ref _WholesaleConditions, value); } }
    
    	[PropertyDefaultValue(0)][DataMember]
        public string Tax { get{ return _Tax; } set{ SetValue("Tax", ref _Tax, value); } }
    
    	[PropertyDefaultValue(0)][DataMember]
        public string Discount { get{ return _Discount; } set{ SetValue("Discount", ref _Discount, value); } }
    
    	#endregion
    }
}
