//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ApaGroup.Framework.Basis.Enumerations;
using ApaGroup.Framework.Dal.DataStructure.Attributes;
using ApaGroup.Framework.Dal.DataStructure.Securities.Attributes;
using ApaService.Framework.Dal.DataStructure.Cores.DataModels;
using ApaGroup.Framework.Dal.DataStructure.Enumerations;
using System;
using System.Runtime.Serialization;

namespace ApaService.Framework.Dal.DataStructure.DataModels
{
    [DatabaseObject("Product")][DataModel][DataContract(IsReference = true)]
    public partial class AdministratorProductDataModelBase : ApasDataModelBase
    {
    	#region Private Fields
    
    	private int _Id;
    
    	private byte[] _RowVersion;
    
    	private System.DateTime _CreateDate;
    
    	private System.DateTime _UpdateDate;
    
    	private Nullable<int> _BrandId;
    
    	private int _ShopId;
    
    	private string _PersianName;
    
    	private string _EnglishName;
    
    	private string _SearchHelper;
    
    	private Nullable<System.Guid> _LogoIdentifier;
    
    	private System.DateTime _ExhibitionStartDate;
    
    	private System.DateTime _ExhibitionExpireDate;
    
    	private bool _IsAvailable;
    
    	private bool _IsModifingCausedDisable;
    
    	private bool _Enable;
    
    	private bool _IsProductNeededToConfirm;
    
    	private bool _IsPriceNeededToConfirm;
    
    	private string _Properties;
    
    	private string _SelectableProperties;
    
    	private string _SupportedSelectableProperties;
    
    	private string _AttachmentIdentifiers;
    
    	private string _ImageIdentifiers;
    
    	private string _Description;
    
    	#endregion
    
    	#region Public Properties
    
    	[DataMember]
        public override int Id { get{ return _Id; } set{ SetValue("Id", ref _Id, value); } }
    
    	[DataMember]
        public override byte[] RowVersion { get{ return _RowVersion; } set{ SetValue("RowVersion", ref _RowVersion, value); } }
    
    	[ValueChangePreventer][DataMember]
        public System.DateTime CreateDate { get{ return _CreateDate; } set{ SetValue("CreateDate", ref _CreateDate, value); } }
    
    	[DataMember]
        public System.DateTime UpdateDate { get{ return _UpdateDate; } set{ SetValue("UpdateDate", ref _UpdateDate, value); } }
    
    	[DataMember]
        public Nullable<int> BrandId { get{ return _BrandId; } set{ SetValue("BrandId", ref _BrandId, value); } }
    
    	[ValueChangePreventer][DataMember]
        public int ShopId { get{ return _ShopId; } set{ SetValue("ShopId", ref _ShopId, value); } }
    
    	[DataMember]
        public string PersianName { get{ return _PersianName; } set{ SetValue("PersianName", ref _PersianName, value); } }
    
    	[PropertyDefaultValue("")][DataMember]
        public string EnglishName { get{ return _EnglishName; } set{ SetValue("EnglishName", ref _EnglishName, value); } }
    
    	[DataMember]
        public string SearchHelper { get{ return _SearchHelper; } set{ SetValue("SearchHelper", ref _SearchHelper, value); } }
    
    	[PropertyDefaultValue(null)][DataMember]
        public Nullable<System.Guid> LogoIdentifier { get{ return _LogoIdentifier; } set{ SetValue("LogoIdentifier", ref _LogoIdentifier, value); } }
    
    	[DataMember]
        public System.DateTime ExhibitionStartDate { get{ return _ExhibitionStartDate; } set{ SetValue("ExhibitionStartDate", ref _ExhibitionStartDate, value); } }
    
    	[DataMember]
        public System.DateTime ExhibitionExpireDate { get{ return _ExhibitionExpireDate; } set{ SetValue("ExhibitionExpireDate", ref _ExhibitionExpireDate, value); } }
    
    	[PropertyDefaultValue(false)][DataMember]
        public bool IsAvailable { get{ return _IsAvailable; } set{ SetValue("IsAvailable", ref _IsAvailable, value); } }
    
    	[PropertyDefaultValue(true)][DataMember]
        public bool IsModifingCausedDisable { get{ return _IsModifingCausedDisable; } set{ SetValue("IsModifingCausedDisable", ref _IsModifingCausedDisable, value); } }
    
    	[PropertyDefaultValue(false)][DataMember]
        public bool Enable { get{ return _Enable; } set{ SetValue("Enable", ref _Enable, value); } }
    
    	[PropertyDefaultValue(false)][DataMember]
        public bool IsProductNeededToConfirm { get{ return _IsProductNeededToConfirm; } set{ SetValue("IsProductNeededToConfirm", ref _IsProductNeededToConfirm, value); } }
    
    	[PropertyDefaultValue(false)][DataMember]
        public bool IsPriceNeededToConfirm { get{ return _IsPriceNeededToConfirm; } set{ SetValue("IsPriceNeededToConfirm", ref _IsPriceNeededToConfirm, value); } }
    
    	[DataMember]
        public string Properties { get{ return _Properties; } set{ SetValue("Properties", ref _Properties, value); } }
    
    	[DataMember]
        public string SelectableProperties { get{ return _SelectableProperties; } set{ SetValue("SelectableProperties", ref _SelectableProperties, value); } }
    
    	[DataMember]
        public string SupportedSelectableProperties { get{ return _SupportedSelectableProperties; } set{ SetValue("SupportedSelectableProperties", ref _SupportedSelectableProperties, value); } }
    
    	[DataMember]
        public string AttachmentIdentifiers { get{ return _AttachmentIdentifiers; } set{ SetValue("AttachmentIdentifiers", ref _AttachmentIdentifiers, value); } }
    
    	[DataMember]
        public string ImageIdentifiers { get{ return _ImageIdentifiers; } set{ SetValue("ImageIdentifiers", ref _ImageIdentifiers, value); } }
    
    	[PropertyDefaultValue("")][DataMember]
        public string Description { get{ return _Description; } set{ SetValue("Description", ref _Description, value); } }
    
    	#endregion
    }
}
