//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using ApaGroup.Framework.Basis.Enumerations;
using ApaGroup.Framework.Dal.DataStructure.Attributes;
using ApaGroup.Framework.Dal.DataStructure.Securities.Attributes;
using ApaService.Framework.Dal.DataStructure.Cores.DataModels;
using ApaGroup.Framework.Dal.DataStructure.Enumerations;
using System;
using System.Runtime.Serialization;

namespace ApaService.Framework.Dal.DataStructure.DataModels
{
    [DatabaseObject("Resource")][DataModel][DataContract(IsReference = true)]
    public partial class AdministratorResourceDataModel : ApasDataModelBase
    {
    	#region Private Fields
    
    	private int _Id;
    
    	private byte[] _RowVersion;
    
    	private string _Title;
    
    	private System.Guid _ResourceIdentifier;
    
    	private int _Size;
    
    	private string _PhysicalAddress;
    
    	#endregion
    
    	#region Public Properties
    
    	[DataMember]
        public override int Id { get{ return _Id; } set{ SetValue("Id", ref _Id, value); } }
    
    	[DataMember]
        public override byte[] RowVersion { get{ return _RowVersion; } set{ SetValue("RowVersion", ref _RowVersion, value); } }
    
    	[PropertyDefaultValue("")][DataMember]
        public string Title { get{ return _Title; } set{ SetValue("Title", ref _Title, value); } }
    
    	[ValueChangePreventer][DataMember]
        public System.Guid ResourceIdentifier { get{ return _ResourceIdentifier; } set{ SetValue("ResourceIdentifier", ref _ResourceIdentifier, value); } }
    
    	[ValueChangePreventer][DataMember]
        public int Size { get{ return _Size; } set{ SetValue("Size", ref _Size, value); } }
    
    	[ValueChangePreventer][DataMember]
        public string PhysicalAddress { get{ return _PhysicalAddress; } set{ SetValue("PhysicalAddress", ref _PhysicalAddress, value); } }
    
    	#endregion
    }
}
