//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApaService.Framework.Dal.Context.Contexts
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using ApaService.Framework.Dal.DataStructure.DataModels;
    
    public partial class AdministratorEntities : DbContext
    {
        public AdministratorEntities()
            : base("name=AdministratorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdministratorAccountDataModelBase> AdministratorAccountDataModelBases { get; set; }
        public virtual DbSet<AdministratorBasketDataModel> AdministratorBasketDataModels { get; set; }
        public virtual DbSet<AdministratorProductDataModelBase> AdministratorProductDataModelBases { get; set; }
        public virtual DbSet<AdministratorProductCategoryDataModel> AdministratorProductCategoryDataModels { get; set; }
        public virtual DbSet<AdministratorProductCommentDataModel> AdministratorProductCommentDataModels { get; set; }
        public virtual DbSet<AdministratorProductRankDataModel> AdministratorProductRankDataModels { get; set; }
        public virtual DbSet<AdministratorProductStatisticDataModel> AdministratorProductStatisticDataModels { get; set; }
        public virtual DbSet<AdministratorShopDataModel> AdministratorShopDataModels { get; set; }
        public virtual DbSet<AdministratorShopCategoryDataModel> AdministratorShopCategoryDataModels { get; set; }
        public virtual DbSet<AdministratorShopCommentDataModel> AdministratorShopCommentDataModels { get; set; }
        public virtual DbSet<AdministratorShopDeliveryMethodDataModel> AdministratorShopDeliveryMethodDataModels { get; set; }
        public virtual DbSet<AdministratorShopPaymentMethodDataModel> AdministratorShopPaymentMethodDataModels { get; set; }
        public virtual DbSet<AdministratorShopRankDataModel> AdministratorShopRankDataModels { get; set; }
        public virtual DbSet<AdministratorShopServeLocationDataModel> AdministratorShopServeLocationDataModels { get; set; }
        public virtual DbSet<AdministratorShopStatisticDataModel> AdministratorShopStatisticDataModels { get; set; }
        public virtual DbSet<AdministratorBasketItemDataModel> AdministratorBasketItemDataModels { get; set; }
        public virtual DbSet<AdministratorBrandDataModel> AdministratorBrandDataModels { get; set; }
        public virtual DbSet<AdministratorResourceDataModel> AdministratorResourceDataModels { get; set; }
        public virtual DbSet<AdministratorCategoryDataModel> AdministratorCategoryDataModels { get; set; }
        public virtual DbSet<AdministratorUserDataModel> AdministratorUserDataModels { get; set; }
        public virtual DbSet<AdministratorLocationDataModel> AdministratorLocationDataModels { get; set; }
        public virtual DbSet<AdministratorTransactionDataModelBase> AdministratorTransactionDataModelBases { get; set; }
    }
}
